### ISSUE TITLE
Does CCDA Validator work in Offline Mode 

### ISSUE THREAD

**Issue by andywuexan** [siteadmin/reference-ccda-validator#47] opened 2018-12-19 00:47 UTC
This is a wonderful application.

We have followed the provided instructions to deploy this application on my local env, everything is working properly. We have also tested a bunch of negative cases, and a few good examples, all tests passed without any issue.

But, one requirement from our side is that we'd like to integrate this application into my core software, and ideally, it should work in an environment without an internet connection.  

We have spent a few hours on this project, and we are wondering if you could provide any insight/solution to the problem described above.

Thanks,
Andy

**Comment by drbgfc** [comment] 2018-12-20 01:05
Thanks. Glad everything worked out.

AFAIK, the application should be able to work without an internet connection as long as it's hosted on a local tomcat server. Did you have any specific issues in trying this? Or, is your interest in running the application in with different version of the code outside of tomcat?

**Comment by andywuexan** [comment] 2018-12-27 18:36
The CCDA application tool is working properly with an Internet connection on my local environment. I have tried the validation tool to verify a few bad and good test cases, all good.

But, after disabling the internet connection (hard refreshed web browser), the application webpage cannot be properly loaded. See the attached screenshot.


![disabledinternetconnection](https://user-images.githubusercontent.com/43556912/50490672-2d9c4700-09c3-11e9-9e14-72f72d2388e4.png)

**Comment by drbgfc** [comment] 2018-12-27 18:48
I see. When I get a chance I will try to reproduce. In the meantime: In the past I have noticed that sometimes Chrome itself does not work correctly or at all with any locally hosted application due to some bug in the version or settings which are required. Due to this, I would first try other browsers as well as ensure chrome is up-to-date. I would also google some settings for using a locally hosted application in Chrome.. It's possible that the static-ui requires an internet connection and if so this could quite likely be resolved. However, please ensure you can use the API as I can't see any reason that should not work offline. So by this I mean running something like postman with the following form-data: 
ccdaFile 
referenceFileName 
validationObjective 
...and a url like this http://localhost:8080/referenceccdaservice/

Thanks,
Dan

**Comment by andywuexan** [comment] 2018-12-27 22:42
Thanks, Dan.

Following your suggestion, I downloaded and installed Postman on my local workstation.

I tested the GET call with the Internet connection. See the screenshot below

![getallwithinternet](https://user-images.githubusercontent.com/43556912/50496513-60573700-09e5-11e9-967b-2aa289d63aaa.png)

I also then tested the same GET call without an internet connection (Disabled internet connection, then restarted Tomcat). See the screenshot below.

![getcallwithoutconnection](https://user-images.githubusercontent.com/43556912/50496520-6cdb8f80-09e5-11e9-89e7-514b8d84485d.png)

The details of the ERROR message:

`<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Exception Report</p><p><b>Message</b> Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I&#47;O error on GET request for &quot;https:&#47;&#47;api.github.com&#47;repos&#47;siteadmin&#47;2015-Certification-C-CDA-Test-Data&#47;git&#47;trees&#47;master?recursive=1&quot;: api.github.com; nested exception is java.net.UnknownHostException: api.github.com</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><p><b>Exception</b></p><pre>org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I&#47;O error on GET request for &quot;https:&#47;&#47;api.github.com&#47;repos&#47;siteadmin&#47;2015-Certification-C-CDA-Test-Data&#47;git&#47;trees&#47;master?recursive=1&quot;: api.github.com; nested exception is java.net.UnknownHostException: api.github.com
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:981)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre><p><b>Root Cause</b></p><pre>org.springframework.web.client.ResourceAccessException: I&#47;O error on GET request for &quot;https:&#47;&#47;api.github.com&#47;repos&#47;siteadmin&#47;2015-Certification-C-CDA-Test-Data&#47;git&#47;trees&#47;master?recursive=1&quot;: api.github.com; nested exception is java.net.UnknownHostException: api.github.com
	org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:607)
	org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:503)
	org.sitenv.referenceccda.services.VocabularyService.getMapOfSenderAndRecieverValidationObjectivesWithReferenceFiles(VocabularyService.java:59)
	org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController.getMapOfSenderAndRecieverValidationObjectivesWithReferenceFiles(ReferenceCCDAValidationController.java:76)
	org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$FastClassBySpringCGLIB$$28bef42b.invoke(&lt;generated&gt;)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:320)
	org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:353)
	org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302)
	org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$EnhancerBySpringCGLIB$$5969ff06.getMapOfSenderAndRecieverValidationObjectivesWithReferenceFiles(&lt;generated&gt;)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre><p><b>Root Cause</b></p><pre>java.net.UnknownHostException: api.github.com
	java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	java.net.PlainSocketImpl.connect(Unknown Source)
	java.net.SocksSocketImpl.connect(Unknown Source)
	java.net.Socket.connect(Unknown Source)
	sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	sun.net.NetworkClient.doConnect(Unknown Source)
	sun.net.www.http.HttpClient.openServer(Unknown Source)
	sun.net.www.http.HttpClient.openServer(Unknown Source)
	sun.net.www.protocol.https.HttpsClient.&lt;init&gt;(Unknown Source)
	sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(Unknown Source)
	org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:80)
	org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:596)
	org.springframework.web.client.RestTemplate.execute(RestTemplate.java:557)
	org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:503)
	org.sitenv.referenceccda.services.VocabularyService.getMapOfSenderAndRecieverValidationObjectivesWithReferenceFiles(VocabularyService.java:59)
	org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController.getMapOfSenderAndRecieverValidationObjectivesWithReferenceFiles(ReferenceCCDAValidationController.java:76)
	org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$FastClassBySpringCGLIB$$28bef42b.invoke(&lt;generated&gt;)
	org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
	org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:320)
	org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:353)
	org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:302)
	org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
	org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	org.sitenv.referenceccda.controllers.ReferenceCCDAValidationController$$EnhancerBySpringCGLIB$$5969ff06.getMapOfSenderAndRecieverValidationObjectivesWithReferenceFiles(&lt;generated&gt;)
	sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	java.lang.reflect.Method.invoke(Unknown Source)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:222)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:137)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:110)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:969)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:860)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:845)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
</pre><p><b>Note</b> The full stack trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat/9.0.13</h3></body></html>`

**Comment by drbgfc** [comment] 2018-12-27 23:09
Interesting. I was acutally suggesting doing a POST for validation to this url http://localhost:8080/referenceccdaservice/ with some key values of something like : ccdaFile:file referenceFileName:test and validationObjective:NonSpecificCCDA
However, in the GET you tried, from a quick look the issue appears to be that it seems to need an internet connection for a git api - when time I will look into it and see why. Thanks.

**Comment by andywuexan** [comment] 2018-12-27 23:21
Thank you, Dan.

I will do the POST call later when I have some spare time, but my guess is that all API calls do need to retrieve more information from Github website. Once again, appreciate your help and efforts.

Thx,
Andy

**Comment by andywuexan** [comment] 2019-01-24 22:14
Hi Dan,

I'm wondering if you got a chance to reproduce the issue we were talking about. 

After cutting off the internet connection to my workstation, we tried Firefox and Edge, but get the same test results - the application cannot be properly loaded. Looks like the application needs to retrieve a few external JS libraries (Bootstrap for CSS, Angular..) to render.

Thx,
Andy

**Comment by drbgfc** [comment] 2019-01-24 23:00
Hi Andy - I was waiting to see if you had tried POSTing with something like Postman to narrow it down. What you described sounds plausible though for the UI. I will look into it - here is what I mean though:
![image](https://user-images.githubusercontent.com/5495334/51714002-d90bdc00-2001-11e9-86b7-f3ca7d557c8b.png)

**Comment by andywuexan** [comment] 2019-01-24 23:52
Hi Dan,

See the attached screenshot.

From what we can see, the POST API call does **NOT** need the internet connection at all, yet the GET API call does.

Fortunately, we just need POST API call to validate all given CCDA files.

Thank you for the help with our project.

Regards,
Andy

![pasted_image_at_2019-01-24__3_46_pm](https://user-images.githubusercontent.com/43556912/51715998-e15b1b80-1fef-11e9-80a7-6e2a507c3451.png)

**Comment by andywuexan** [comment] 2019-01-24 23:58
FYI, the above POST test was done in an offline mode.

**Comment by drbgfc** [comment] 2019-01-25 00:01
Awesome. I think it's still worth us looking into updating the GET/Ui to work offline so thanks for bringing that up - and good to confirm POST is working as expected. I will close this particular issue for now though.

**Closed by drbgfc** 2019-01-25 00:01 UTC
