### ISSUE TITLE
Can not get to webpage.

### ISSUE THREAD

**Issue by jxfish2** [siteadmin/reference-ccda-validator#44] opened 2018-11-09 15:52 UTC
I installed the CCDA Validator project on a brand new CentOS 7 server, and everything appears to be working correctly, from a server perspective.

The application is up and running, without any errors.

The Code Sets and Value Sets all appear to have been loaded correctly.

The web ports are listening on the server, and when I attempt to open a URL to this server, at the OS level, it shows the connection as established from my PC.

But, from the Firefox browser, it says that it "Can't connect to the server".

And, from the Chrome browser, it gives an "HTTP Status 404 - Not Found".

Remember, at the server level, it shows that the connection has been established.

At this point, I must assume that one of two things is happening:

1) Either the application is not serving up the webpage.

2) Something at the network level, is preventing the page from being displayed.

The application is serving up the webpage on port 8080.

Can anyone tell me where the base html file is located?

When you attempt to connect to the following URL, what file is it supposed to be opening?

http://<ServerName>:8080/referenceccdaservice/

**Comment by jxfish2** [comment] 2018-11-09 16:02
Actually, it appears as if the swagger-ui.html file is not in the referenceccdaservice directory.

The only things under this referenceccdaservice directory are:

root @ <ServerName> | /opt/tomcat/webapps/referenceccdaservice
--> ll
total 12
drwxrwxr-x 3 tomcat tomcat 4096 Nov  7 08:56 META-INF
drwxrwxr-x 4 tomcat tomcat 4096 Nov  7 08:56 static
drwxrwxr-x 4 tomcat tomcat 4096 Nov  7 08:56 WEB-INF

I wonder if I missed a step somewhere.

How do I populate the referenceccdaservice folder?

**Comment by drbgfc** [comment] 2018-11-09 16:34
http://localhost:8080/referenceccdaservice/ is the endpoint for the service so you would need to hit that API with something like postman or some source code.
In postman you would send a ccdaFile, referenceFIleName, validationObjective, and optionally a vocabularyConfig all as form-data.

To try the static ui type which calls the API with an angular frontend type this in your browser:
http://localhost:8080/referenceccdaservice/ui

To try swagger type this in your browser:
http://localhost:8080/referenceccdaservice/swagger-ui.html#/reference-ccda-validation-controller

Thanks,
Dan

**Comment by jxfish2** [comment] 2018-11-09 17:39
Hi Dan,

Thanks for the quick response.

Unfortunately, there are no html files under the referenceccdaservice directory structure.

I am a systems engineer, not a web developer, but my understanding is that there should be some kind of html file under the referenceccdaservice directory.

If this is correct, then there is something wrong here, in that I do not have any html documents under this directory structure.

Is there a particular step, or procedure, that populates the html files in this particular directory?

**Comment by jxfish2** [comment] 2018-11-09 18:44
Actually, after the initial startup, there were no errors.

After loading all of the code sets, there were no errors.

I just checked the log files again, but now there are errors.

Here is an excerpt of what I am seeing in the logs now:

catalina.2018-11-09.log:SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
catalina.2018-11-09.log:SEVERE: Context [/referenceccdaservice] startup failed due to previous errors
catalina.2018-11-09.log:SEVERE: The web application [/referenceccdaservice] registered the JDBC driver [org.hsqldb.jdbc.JDBCDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
catalina.2018-11-09.log:SEVERE: Invalid message received with signature 18245
catalina.out:SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
catalina.out:SEVERE: Context [/referenceccdaservice] startup failed due to previous errors
catalina.out:SEVERE: The web application [/referenceccdaservice] registered the JDBC driver [org.hsqldb.jdbc.JDBCDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
catalina.out:SEVERE: Invalid message received with signature 18245
localhost.2018-11-09.log:SEVERE: Exception sending context initialized event to listener instance of class org.springframework.web.context.ContextLoaderListener
localhost.2018-11-09.log:org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vocabularyLoadRunner' defined in org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
localhost.2018-11-09.log:Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
referenceccdaservice.2018-11-09.log:10:42:18,527 WARN  [AnnotationConfigWebApplicationContext:546] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vocabularyLoadRunner' defined in org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
referenceccdaservice.2018-11-09.log:10:42:29,724 ERROR [ContextLoader:353] Context initialization failed
referenceccdaservice.2018-11-09.log:org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vocabularyLoadRunner' defined in org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
referenceccdaservice.2018-11-09.log:Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

As I am not a developer, I would appreciate any help or suggestions you can give me, to fix the errors.

Joe

**Comment by jxfish2** [comment] 2018-11-09 19:06
Please note that the CCDA Validator application is being installed directly in the /opt directory structure on the Linux virtual server.

One of the log file entries above, notes that full details will be found in the appropriate "container" directory.

We are not using containers on this server.

**Comment by drbgfc** [comment] 2018-11-09 19:43
Tomcat is a Java Servlet Container - so by container directory it means mean the logs in catalina home (opt/tomcat/logs/someRelevantLog...).

If you could attach the full log for today (match date in log directory) that would be best.

You are getting an OutOfMemoryError. This is a memory intensive application since all of the vocabularies are loaded into an in-memory DB. Does your server have enough freely available RAM? Make sure to consider not just the the system specs but the total available after usage by other applications. We have successfully run the service on 2GB and 4GB machines but I don't believe we have tried any lower.

**Comment by drbgfc** [comment] 2018-11-09 19:48
btw the validationui is located in the web app 'static' folder. Your strucure for your web app (referenceccdaservice) looks good. Tomcat, Java, and Angular all work together with these structures (META-INF | static | WEB-INF) to describe to the browser what it needs to display content.

**Comment by jxfish2** [comment] 2018-11-09 19:48
Here's what we have for memory on this server:

--> free -h
                    total        used        free      shared  buff/cache   available
Mem:           6.8G        1.6G        4.2G     2.8M    992M         4.9G
Swap:           2.0G        123M      1.9G

**Comment by drbgfc** [comment] 2018-11-09 19:53
Thanks - if you have 4.2G free then it should work ... hmm I will await the full log file - Apologies I may not be able to look at this much today though.

**Comment by drbgfc** [comment] 2018-11-09 19:54
The log I'm looking for is: /opt/tomcat/logs/catalina.2018-11-09.log

**Comment by jxfish2** [comment] 2018-11-09 19:59
Attaching 3 documents:

catalina.2018-11-09.log
localhost.2018-11-09.log
referenceccdaservice.2018-11-09.log

[localhost.2018-11-09.log](https://github.com/siteadmin/reference-ccda-validator/files/2567333/localhost.2018-11-09.log)
[catalina.2018-11-09.log](https://github.com/siteadmin/reference-ccda-validator/files/2567334/catalina.2018-11-09.log)
[referenceccdaservice.2018-11-09.log](https://github.com/siteadmin/reference-ccda-validator/files/2567335/referenceccdaservice.2018-11-09.log)

**Comment by drbgfc** [comment] 2018-11-09 20:02
This might be a tomcat configuration issue, what version are you using? Also what version of Java? In certain cases depending on the prior conditions (and in any case won't hurt, will just ignore if not applicable) you increase your heap space in Java.
Try this a try until I get time to look further:
in /opt/apache-tomcat-8.0.43/bin
create a file called:
setenv.sh
Save it with the following data, restart your linux server, then try running tomcat:

#!/bin/bash


JAVA_OPTS="$JAVA_OPTS -Xmx5120m -XX:MaxPermSize=1024m"

**Comment by jxfish2** [comment] 2018-11-09 20:05
--> service tomcat stop

Using CATALINA_BASE:   /opt/tomcat
Using CATALINA_HOME:   /opt/tomcat
Using CATALINA_TMPDIR: /opt/tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.191.b12-0.el7_5.x86_64/jre
Using CLASSPATH:       /opt/tomcat/bin/bootstrap.jar:/opt/tomcat/bin/tomcat-juli.jar
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0

**Comment by drbgfc** [comment] 2018-11-09 20:06
Ok then it's irrelevant, 8.0 should be able grow as needed so that wasn't the issue

**Comment by jxfish2** [comment] 2018-11-09 20:07
--> java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by jxfish2** [comment] 2018-11-09 20:07
apache-tomcat-7.0.91

**Comment by jxfish2** [comment] 2018-11-09 20:09
Maybe it's the version of Tomcat.
It appears as if there are Tomcat versions 8 and 9 online.
Would you recommend 8 or 9?
I could do either one.

**Comment by drbgfc** [comment] 2018-11-09 20:15
The issue is that it is running our of memory when loading the vocabulary. Why I am not sure, but when it hits SNOMED-CT it runs out and throws the exception which then causes all kinds of other issues. 
It's possible there is something it doesn't like about your SNOMED-CT. How large is the file? What's the exact filename?
It's also possible there is a memory leak and that you must restart your linux server to accomodate for it due to multiple attempts trying to fire it up. If it's working, the full load will take at least 5 minutes.
Tomcat7 should work, but, for the sake of an equal comparison, our servers are running:
apache-tomcat-8.0.43
So you might want to try that.

Related Exception Snippet:
10:28:49,173 INFO  [VocabularyLoadRunner:92] Loading vocabularies at: /opt/CCDA_Validator/configuration/vocabulary/code_repository...
10:28:49,174 INFO  [VocabularyLoadRunner:44] Loading files in : LOINC...
10:28:49,186 INFO  [LoincLoader:60] Loading latest LOINC CSV / updating indexes
10:29:31,563 INFO  [VocabularyLoadRunner:44] Loading files in : ICD9CM_SG...
10:29:31,677 INFO  [VocabularyLoadRunner:44] Loading files in : ICD10PCS...
10:29:37,543 INFO  [VocabularyLoadRunner:44] Loading files in : RXNORM...
10:30:16,103 INFO  [VocabularyLoadRunner:44] Loading files in : ICD9CM_DX...
10:30:21,311 INFO  [VocabularyLoadRunner:44] Loading files in : SNOMED-CT...
10:42:18,527 WARN  [AnnotationConfigWebApplicationContext:546] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vocabularyLoadRunner' defined in org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded
10:42:24,322 INFO  [EmbeddedDatabaseFactory:217] Shutting down embedded database: url='jdbc:hsqldb:mem:testdb'
10:42:29,724 ERROR [ContextLoader:353] Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'vocabularyLoadRunner' defined in org.sitenv.vocabularies.configuration.CodeValidatorApiConfiguration: Invocation of init method failed; nested exception is java.lang.OutOfMemoryError: GC overhead limit exceeded at ...

**Comment by jxfish2** [comment] 2018-11-09 20:18
The SNOMED-CT text file is fairly large.

--> ll
total 324668
-rwxr-xr-x 1 tomcat tomcat 332453333 Nov  6 17:06 sct2_Description_Full-en_US1000124_20180901.txt

**Comment by jxfish2** [comment] 2018-11-09 20:36
We are a medical software vendor, and we have thousands of these codes already in our databases.

As such, our development team created a program to extract the current data directly from our own databases.

While extracting the data, they populated each of the files you requested programatically.

Going forward, we can generate the code sets with the latest data, whenever we want, programatically.

Now, having said that, I am going to move the SNOMED-CT file out of the way, just to see if it still throws an error.

**Comment by jxfish2** [comment] 2018-11-09 20:41
After moving the SNOMED-CT directory to another temporary location, I restarted tomcat.

I am now getting the following errors:

15:38:07,283 INFO  [VocabularyLoadRunner:92] Loading vocabularies at: /opt/CCDA_Validator/configuration/vocabulary/code_repository...
15:38:07,284 INFO  [VocabularyLoadRunner:44] Loading files in : LOINC...
15:38:07,302 INFO  [LoincLoader:60] Loading latest LOINC CSV / updating indexes
15:38:49,491 INFO  [VocabularyLoadRunner:44] Loading files in : ICD9CM_SG...
15:38:49,595 INFO  [VocabularyLoadRunner:44] Loading files in : ICD10PCS...
15:38:53,390 INFO  [VocabularyLoadRunner:44] Loading files in : RXNORM...
15:39:30,562 INFO  [VocabularyLoadRunner:44] Loading files in : ICD9CM_DX...
15:39:31,258 INFO  [VocabularyLoadRunner:44] Loading files in : CPT...
15:39:31,489 INFO  [VocabularyLoadRunner:44] Loading files in : ICD10CM...
15:39:42,003 INFO  [VocabularyLoadRunner:94] Vocabularies loaded...
15:39:42,003 INFO  [VocabularyLoadRunner:99] Loading value sets at: /opt/CCDA_Validator/configuration/valueset_repository...
15:39:42,005 ERROR [VocabularyLoadRunner:107] Failed to load configured vocabulary directory.
java.lang.NullPointerException
        at org.sitenv.vocabularies.loader.VocabularyLoadRunner.loadDirectory(VocabularyLoadRunner.java:31)
        at org.sitenv.vocabularies.loader.VocabularyLoadRunner.afterPropertiesSet(VocabularyLoadRunner.java:100)

I truncated everything after this point.

**Comment by jxfish2** [comment] 2018-11-09 20:45
root @ LocalServerName | /opt/CCDA_Validator/configuration/vocabulary/valueset_repository
--> ls -lh VSAC | more
total 28M
-rwxr-xr-x 1 tomcat tomcat 290K Nov  7 08:52 1.3.6.1.4.1.12009.10.2.5.xlsx
-rwxr-xr-x 1 tomcat tomcat 2.1M Nov  7 08:52 2.16.840.1.113762.1.4.1010.1.xlsx
-rwxr-xr-x 1 tomcat tomcat 3.9M Nov  7 08:52 2.16.840.1.113762.1.4.1010.2.xlsx
-rwxr-xr-x 1 tomcat tomcat 3.1M Nov  7 08:52 2.16.840.1.113762.1.4.1010.4.xlsx
-rwxr-xr-x 1 tomcat tomcat 106K Nov  7 08:52 2.16.840.1.113762.1.4.1010.6.xlsx
-rwxr-xr-x 1 tomcat tomcat 112K Nov  7 08:52 2.16.840.1.113762.1.4.1010.8.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113762.1.4.1021.30.xlsx
-rwxr-xr-x 1 tomcat tomcat 110K Nov  7 08:52 2.16.840.1.113762.1.4.1095.49.xlsx
-rwxr-xr-x 1 tomcat tomcat 101K Nov  7 08:52 2.16.840.1.113762.1.4.1095.51.xlsx
-rwxr-xr-x 1 tomcat tomcat 106K Nov  7 08:52 2.16.840.1.113762.1.4.1095.58.xlsx
-rwxr-xr-x 1 tomcat tomcat 102K Nov  7 08:52 2.16.840.1.113762.1.4.1095.59.xlsx
-rwxr-xr-x 1 tomcat tomcat 101K Nov  7 08:52 2.16.840.1.113762.1.4.1095.65.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113762.1.4.1095.75.xlsx
-rwxr-xr-x 1 tomcat tomcat 100K Nov  7 08:52 2.16.840.1.113762.1.4.1095.81.xlsx
-rwxr-xr-x 1 tomcat tomcat 102K Nov  7 08:52 2.16.840.1.113762.1.4.1095.82.xlsx
-rwxr-xr-x 1 tomcat tomcat 105K Nov  7 08:52 2.16.840.1.113762.1.4.1095.85.xlsx
-rwxr-xr-x 1 tomcat tomcat 100K Nov  7 08:52 2.16.840.1.113762.1.4.1095.87.xlsx
-rwxr-xr-x 1 tomcat tomcat 102K Nov  7 08:52 2.16.840.1.113762.1.4.1099.10.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113762.1.4.1099.11.xlsx
-rwxr-xr-x 1 tomcat tomcat 104K Nov  7 08:52 2.16.840.1.113762.1.4.1099.12.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113762.1.4.1099.4.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113762.1.4.1.xlsx
-rwxr-xr-x 1 tomcat tomcat 100K Nov  7 08:52 2.16.840.1.113883.1.11.10267.xlsx
-rwxr-xr-x 1 tomcat tomcat 100K Nov  7 08:52 2.16.840.1.113883.1.11.10416.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113883.1.11.10637.xlsx
-rwxr-xr-x 1 tomcat tomcat 101K Nov  7 08:52 2.16.840.1.113883.1.11.10901.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113883.1.11.11610.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:51 2.16.840.1.113883.1.11.12199.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113883.1.11.12212.xlsx
-rwxr-xr-x 1 tomcat tomcat  99K Nov  7 08:52 2.16.840.1.113883.1.11.12249.xlsx
-rwxr-xr-x 1 tomcat tomcat 125K Nov  7 08:52 2.16.840.1.113883.1.11.12839.xlsx
-rwxr-xr-x 1 tomcat tomcat 129K Nov  7 08:52 2.16.840.1.113883.1.11.14914.xlsx

Just a sampling of valueset_repository/VSAC directory.

**Comment by drbgfc** [comment] 2018-11-09 20:56
to narrow down the issue, can you try the following:
-delete or move/remove all files except one valueset from valueset_repository/VSAC
-rename the remaining file to the name of the valueset e.g. Ability.xlsx

Also, can you provide your referenceccdaservice.xml?

**Comment by drbgfc** [comment] 2018-11-09 21:04
Here is an example of a working context (referenceccdaservice.xml ) place in /opt/apache-tomcat-7.0.53/conf/Catalina/localhost 
Note how 'VSAC' is not listed even though it is in the system path (as it should be). This may not be your issue but is a common one so mentioning.

```xml
<Context reloadable="true">
    <Parameter name="vocabulary.localCodeRepositoryDir" value="/opt/apache-tomcat-7.0.53/mdht/Environment/VocabularyConfiguration/Vocabulary/code_repository/" override="true"/>
        <Parameter name="vocabulary.localValueSetRepositoryDir" value="/opt/apache-tomcat-7.0.53/mdht/Environment/VocabularyConfiguration/Vocabulary/valueset_repository/" override="true"/>
        <Parameter name="referenceccda.configFile" value="/opt/apache-tomcat-7.0.53/mdht/Environment/VocabularyConfiguration/ccdaReferenceValidatorConfig.xml" override="true"/>
        <Parameter name="referenceccda.isDynamicVocab" value="false" override="true"/>
        <Parameter name="referenceccda.configFolder" value="/opt/apache-tomcat-7.0.53/mdht/Environment/VocabularyConfiguration/" override="true"/>
        <Parameter name="content.scenariosDir" value="/opt/apache-tomcat-7.0.53/mdht/Environment/VocabularyConfiguration/scenarios/" override="true"/>
</Context>
```

**Comment by jxfish2** [comment] 2018-11-09 21:35
Contents of the referenceccdaservice.xml file:



<Context reloadable="true">
    <Parameter name="vocabulary.localCodeRepositoryDir" value="/opt/CCDA_Validator/configuration/vocabulary/code_repository" override="true"/>
        <Parameter name="vocabulary.localValueSetRepositoryDir" value="/opt/CCDA_Validator/configuration/valueset_repository" override="true"/>
        <Parameter name="referenceccda.configFile" value="/opt/CCDA_Validator/configuration/ccdaReferenceValidatorConfig.xml" override="true"/>
    <Parameter name="referenceccda.isDynamicVocab" value="false" override="true"/>
    <Parameter name="referenceccda.configFolder" value="/opt/CCDA_Validator/configuration" override="true"/>
        <Parameter name="content.scenariosDir" value="/opt/CCDA_Validator/configuration/scenarios" override="true"/>
</Context>

**Comment by bobjase** [comment] 2018-12-05 02:42
Jxfish: did you find a solution?

**Comment by drbgfc** [comment] 2018-12-12 22:44
@bobjase 
Jxfish2's original question has been resolved (how to get to a landing page) and this really should be a new ticket at this point. The subsequent issue OOME, was sort of resolved in the sense that the user was using a different version of SNOMED than us so we have not tested that version and thus don't support it. The most recent issue of an NPE is unresolved but I am thinking it might be related to vocabulary naming. 

I will answer your question (1) on your new issue ticket here:
https://github.com/siteadmin/reference-ccda-validator/issues/46

@jxfish2 
Your referenceccdaservice.xml file looks good. I think this issue is related to the naming of the vocabulary files (using OIDs vs displayNames). Is it possible for you to try renaming and loading just one that is renamed to a displayName style?

Thanks.

**Closed** 2018-12-27 18:35 UTC
